# Generated by Django 3.2.25 on 2024-12-06 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('elevation', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('air_temp', models.FloatField()),
                ('relative_humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.CharField(max_length=255)),
                ('wind_gust', models.FloatField()),
                ('surface_temp', models.FloatField()),
                ('volt', models.FloatField()),
                ('wind_cardinal_direction', models.FloatField()),
                ('dew_point_temperature', models.FloatField()),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='compose.weatherstation')),
            ],
        ),
    ]
