services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - .:/server
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=core_db
      - DB_NAME=core_db
      - DB_USER=devuser
      - DB_PASS=changeme
      - DEBUG=1
    depends_on:
      - core_db
      - build_db
      - analysis_db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  core_db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - dev-core-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=yuki_core_db
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

  build_db:
    image: postgres:13-alpine
    ports:
      - "5433:5432"
    volumes:
      - dev-build-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=yuki_build_db
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

  analysis_db:
    image: postgres:13-alpine
    ports:
      - "5434:5432"
    volumes:
      - dev-analysis-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=yuki_analysis_db
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-core-db-data:
  dev-build-db-data:
  dev-analysis-db-data:
  dev-static-data: